# Generated by Django 5.0.7 on 2024-07-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rural_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantation',
            name='name',
            field=models.CharField(choices=[('Algodão', 'Algodão'), ('Café', 'Café'), ('Cana de Açúcar', 'Cana de Açúcar'), ('Milho', 'Milho'), ('Soja', 'Soja')], max_length=50, verbose_name='Nome da Cultura'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='rural_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rural_property.ruralproperty', verbose_name='Propriedade Rural'),
        ),
    ]
