# Generated by Django 5.0.7 on 2024-07-21 22:07

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Proprietário Rural',
                'verbose_name_plural': 'Proprietários Rurais',
            },
        ),
    ]
